pages:
 # key is the dirname of pages in src/pages
 home:
  # 首页配置
  zh-cn:
   title: 'OpenKruise'
   keywords: '官网,首页'
   description: 'OpenKruise官网'
  # home config
  en-us:
   title: 'OpenKruise'
   keywords: 'Official,OpenKruise'
   description: 'OpenKruise Official Website'
 blog:
  # 博客列表页配置
  zh-cn:
   title: '博客'
   keywords: 'OpenKruise,博客'
   description: 'OpenKruise 博客'
  en-us:
   # blog list page config
   title: 'Blog'
   keywords: 'OpenKruise,Blog'
   description: 'OpenKruise Blog'
